import { MigrationInterface, QueryRunner } from "typeorm";

export class FinalArchitecturalRefinements1778150251999 implements MigrationInterface {
    name = 'FinalArchitecturalRefinements1778150251999'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "FK_8e105b187066e0e5ad2be737a03"`);
        await queryRunner.query(`CREATE TABLE "creator_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "bio" text, "portfolio_url" character varying, "socialLinks" jsonb NOT NULL DEFAULT '{}', "isVerified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_6fae0dfbe41d4c7b37a6e3251c" UNIQUE ("user_id"), CONSTRAINT "PK_5f58900809b867a2683b6e0e94a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "verified" boolean NOT NULL DEFAULT false, "billing_metadata" jsonb, "website_url" character varying, "logo_url" character varying, "owner_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6" UNIQUE ("name"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."creator_campaigns_status_enum" AS ENUM('pending', 'active', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "creator_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "brand_id" uuid NOT NULL, "name" character varying NOT NULL, "status" "public"."creator_campaigns_status_enum" NOT NULL DEFAULT 'pending', "budget" numeric(10,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_04e6c3a196e76b48daf0d926233" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "interactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "trend_id" uuid, "product_id" uuid, "interaction_type" character varying NOT NULL, "source_type" character varying, "content" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_911b7416a6671b4148b18c18ecb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trend_phase_history_old_phase_enum" AS ENUM('emerging', 'rising', 'peak', 'fading')`);
        await queryRunner.query(`CREATE TYPE "public"."trend_phase_history_new_phase_enum" AS ENUM('emerging', 'rising', 'peak', 'fading')`);
        await queryRunner.query(`CREATE TABLE "trend_phase_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trend_id" uuid NOT NULL, "old_phase" "public"."trend_phase_history_old_phase_enum", "new_phase" "public"."trend_phase_history_new_phase_enum" NOT NULL, "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb DEFAULT '{}', CONSTRAINT "PK_87182545b7595d21df90af85858" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trend_signals_signal_type_enum" AS ENUM('velocity', 'saves', 'growth', 'momentum')`);
        await queryRunner.query(`CREATE TABLE "trend_signals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trend_id" uuid NOT NULL, "source" character varying NOT NULL DEFAULT 'other', "signal_type" "public"."trend_signals_signal_type_enum" NOT NULL, "signal_value" numeric(10,2) NOT NULL, "metadata" jsonb DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d1ba65e115f839c6be87f7cdc47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_badges_badge_type_enum" AS ENUM('EARLY_SPOTTER', 'STREETWEAR_EXPERT', 'LUXURY_CURATOR', 'TREND_HUNTER')`);
        await queryRunner.query(`CREATE TABLE "user_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "badge_type" "public"."user_badges_badge_type_enum" NOT NULL, "earned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "source_trend_id" uuid, "metadata" jsonb DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0ca139216824d745a930065706a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."score_events_reason_enum" AS ENUM('EARLY_DISCOVERY', 'SAVE_BONUS', 'SHARE_BONUS', 'TREND_SPOTTED', 'ADMIN_ADJUSTMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."score_events_source_type_enum" AS ENUM('TREND', 'PRODUCT', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "score_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "points_delta" numeric(10,2) NOT NULL, "reason" "public"."score_events_reason_enum" NOT NULL, "source_type" "public"."score_events_source_type_enum" NOT NULL, "source_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1b2270cf7ddc638ef13a1424da1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."early_discovery_rewards_phase_at_discovery_enum" AS ENUM('emerging', 'rising', 'peak', 'fading')`);
        await queryRunner.query(`CREATE TYPE "public"."early_discovery_rewards_reward_type_enum" AS ENUM('POINTS', 'BADGE', 'PERK')`);
        await queryRunner.query(`CREATE TABLE "early_discovery_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "trend_id" uuid NOT NULL, "phase_at_discovery" "public"."early_discovery_rewards_phase_at_discovery_enum" NOT NULL, "bonus_points" numeric(10,2) NOT NULL DEFAULT '0', "reward_type" "public"."early_discovery_rewards_reward_type_enum" NOT NULL DEFAULT 'POINTS', "claimed" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84a897e5e8abcf866029803a1e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discount_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "brand_id" uuid, "discount_type" character varying NOT NULL DEFAULT 'PERCENTAGE', "discount_value" numeric(10,2) NOT NULL, "min_score_required" integer NOT NULL DEFAULT '0', "max_uses" integer, "use_count" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b967edd0d46547d4a92b4a1c6b3" UNIQUE ("code"), CONSTRAINT "PK_c0170a28d937472e9ce50fdce17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "creator_analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "totalReach" integer NOT NULL DEFAULT '0', "totalEngagement" integer NOT NULL DEFAULT '0', "averageEngagementRate" numeric(5,2) NOT NULL DEFAULT '0', "audienceDemographics" jsonb NOT NULL DEFAULT '{}', "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_662863428b4a9f3b241b78894b" UNIQUE ("creator_profile_id"), CONSTRAINT "PK_65a00a6f6026c4174d08f15a3d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "advertiser_id"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "bid_amount"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "priority_score"`);
        await queryRunner.query(`ALTER TABLE "user_profile" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "user_profile" DROP COLUMN "badges"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "PK_d2b512a8b0994f668cef59f135a"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "PK_3661d9991554a583d54a7e4eb39" PRIMARY KEY ("trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "brand_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "placement_bid" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "placement_slot_weight" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`COMMENT ON COLUMN "sponsored_content"."placement_slot_weight" IS 'Weight for paid placement logic, NOT organic ranking'`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "trend_id" uuid`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "campaign_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."clickouts_source_type_enum" AS ENUM('ORGANIC_FEED', 'SPONSORED_FEED', 'CREATOR_PROFILE', 'SEARCH', 'RECOMMENDED')`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "source_type" "public"."clickouts_source_type_enum" NOT NULL DEFAULT 'ORGANIC_FEED'`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "creator_id" uuid`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "session_id" text`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "ip_hash" text`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "converted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD "converted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "saves" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_b0ac3df08c51a42216cab1bf03a"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_e8cf2737d1d478c7a7511e9c65c" PRIMARY KEY ("user_id", "trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "saves" ADD "product_id" uuid`);
        await queryRunner.query(`ALTER TABLE "products" ADD "creator_id" uuid`);
        await queryRunner.query(`ALTER TABLE "products" ADD "is_sponsored" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ADD "is_authentic" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "products" ADD "merchant_name" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ADD "affiliate_network" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ADD "commerce_metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "phase_updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "content_type" character varying NOT NULL DEFAULT 'ORGANIC'`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "status" character varying NOT NULL DEFAULT 'PUBLISHED'`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "FK_d2b512a8b0994f668cef59f135a"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "PK_3661d9991554a583d54a7e4eb39"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "PK_74d230453e3a051cfef34e8fe77" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP CONSTRAINT "FK_21d5402615f2a6ec059af906b02"`);
        await queryRunner.query(`ALTER TABLE "clickouts" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "FK_7b8bc823fd09b6b5751919d4a60"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "FK_dbbc0f92c226a7590f0e468aff8"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_e8cf2737d1d478c7a7511e9c65c"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_06e561922fa92be30f2d032a1e9" PRIMARY KEY ("trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "saves" ALTER COLUMN "trend_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_06e561922fa92be30f2d032a1e9"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_d2ca4e689a49cafa0702b4ef91f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "source"`);
        await queryRunner.query(`DROP TYPE "public"."trends_source_enum"`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "source" character varying NOT NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "phase"`);
        await queryRunner.query(`CREATE TYPE "public"."trends_phase_enum" AS ENUM('emerging', 'rising', 'peak', 'fading')`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "phase" "public"."trends_phase_enum" NOT NULL DEFAULT 'emerging'`);
        await queryRunner.query(`ALTER TYPE "public"."user_profile_role_enum" RENAME TO "user_profile_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_role_enum" AS ENUM('user', 'admin', 'creator', 'brand')`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" TYPE "public"."user_profile_role_enum" USING "role"::"text"::"public"."user_profile_role_enum"`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "CHK_e6b06af5c864e0eab5e48ed6f5" CHECK (("trend_id" IS NOT NULL AND "product_id" IS NULL) OR ("trend_id" IS NULL AND "product_id" IS NOT NULL))`);
        await queryRunner.query(`ALTER TABLE "creator_profiles" ADD CONSTRAINT "FK_6fae0dfbe41d4c7b37a6e3251c5" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "FK_d2b512a8b0994f668cef59f135a" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "FK_03adf1632f01ddc43592d85d43d" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "FK_c28afa0db2ceaa90125fad8f8b9" FOREIGN KEY ("owner_id") REFERENCES "user_profile"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_campaigns" ADD CONSTRAINT "FK_a795a2571996d50efb9e3db9385" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_campaigns" ADD CONSTRAINT "FK_8c1de04673f81e4a9a4042b2731" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD CONSTRAINT "FK_21d5402615f2a6ec059af906b02" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD CONSTRAINT "FK_7b5586a57157b532e50a55004cc" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD CONSTRAINT "FK_f3b0947701b4718bdb7c1bcfdc9" FOREIGN KEY ("campaign_id") REFERENCES "creator_campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD CONSTRAINT "FK_e421ad2735bb458c5eb10ae08f7" FOREIGN KEY ("creator_id") REFERENCES "user_profile"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "FK_7b8bc823fd09b6b5751919d4a60" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "FK_dbbc0f92c226a7590f0e468aff8" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "FK_c2f20089824356c6932060e87bd" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_db887c3b31abbbd920e303a0179" FOREIGN KEY ("creator_id") REFERENCES "creator_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interactions" ADD CONSTRAINT "FK_59962fa0fe4a491273c402e93fa" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interactions" ADD CONSTRAINT "FK_594f5bfc3cf72d8a5b4f89fae3e" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interactions" ADD CONSTRAINT "FK_acb370492c26bcb1a391575f41f" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trend_phase_history" ADD CONSTRAINT "FK_80256b484a4f2abfdaff0dec5d8" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trend_signals" ADD CONSTRAINT "FK_1da0d2e8aad0a16b5a7c4894127" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_1b70a2e69c7b111e9b1de692d05" FOREIGN KEY ("source_trend_id") REFERENCES "trends"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_events" ADD CONSTRAINT "FK_59c441047ee40db35ba530d8a2c" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "early_discovery_rewards" ADD CONSTRAINT "FK_dfeb3d657b45a96e280cf9d3fe2" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "early_discovery_rewards" ADD CONSTRAINT "FK_ab4e4a6acc91ad441663d2024e1" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_codes" ADD CONSTRAINT "FK_481b14681ec75c5c9b6f8319035" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_analytics" ADD CONSTRAINT "FK_662863428b4a9f3b241b78894bf" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "creator_analytics" DROP CONSTRAINT "FK_662863428b4a9f3b241b78894bf"`);
        await queryRunner.query(`ALTER TABLE "discount_codes" DROP CONSTRAINT "FK_481b14681ec75c5c9b6f8319035"`);
        await queryRunner.query(`ALTER TABLE "early_discovery_rewards" DROP CONSTRAINT "FK_ab4e4a6acc91ad441663d2024e1"`);
        await queryRunner.query(`ALTER TABLE "early_discovery_rewards" DROP CONSTRAINT "FK_dfeb3d657b45a96e280cf9d3fe2"`);
        await queryRunner.query(`ALTER TABLE "score_events" DROP CONSTRAINT "FK_59c441047ee40db35ba530d8a2c"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_1b70a2e69c7b111e9b1de692d05"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3"`);
        await queryRunner.query(`ALTER TABLE "trend_signals" DROP CONSTRAINT "FK_1da0d2e8aad0a16b5a7c4894127"`);
        await queryRunner.query(`ALTER TABLE "trend_phase_history" DROP CONSTRAINT "FK_80256b484a4f2abfdaff0dec5d8"`);
        await queryRunner.query(`ALTER TABLE "interactions" DROP CONSTRAINT "FK_acb370492c26bcb1a391575f41f"`);
        await queryRunner.query(`ALTER TABLE "interactions" DROP CONSTRAINT "FK_594f5bfc3cf72d8a5b4f89fae3e"`);
        await queryRunner.query(`ALTER TABLE "interactions" DROP CONSTRAINT "FK_59962fa0fe4a491273c402e93fa"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_db887c3b31abbbd920e303a0179"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "FK_c2f20089824356c6932060e87bd"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "FK_dbbc0f92c226a7590f0e468aff8"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "FK_7b8bc823fd09b6b5751919d4a60"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP CONSTRAINT "FK_e421ad2735bb458c5eb10ae08f7"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP CONSTRAINT "FK_f3b0947701b4718bdb7c1bcfdc9"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP CONSTRAINT "FK_7b5586a57157b532e50a55004cc"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP CONSTRAINT "FK_21d5402615f2a6ec059af906b02"`);
        await queryRunner.query(`ALTER TABLE "creator_campaigns" DROP CONSTRAINT "FK_8c1de04673f81e4a9a4042b2731"`);
        await queryRunner.query(`ALTER TABLE "creator_campaigns" DROP CONSTRAINT "FK_a795a2571996d50efb9e3db9385"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "FK_c28afa0db2ceaa90125fad8f8b9"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "FK_03adf1632f01ddc43592d85d43d"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "FK_d2b512a8b0994f668cef59f135a"`);
        await queryRunner.query(`ALTER TABLE "creator_profiles" DROP CONSTRAINT "FK_6fae0dfbe41d4c7b37a6e3251c5"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "CHK_e6b06af5c864e0eab5e48ed6f5"`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_role_enum_old" AS ENUM('user', 'admin', 'creator')`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" TYPE "public"."user_profile_role_enum_old" USING "role"::"text"::"public"."user_profile_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user_profile" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_profile_role_enum_old" RENAME TO "user_profile_role_enum"`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "phase"`);
        await queryRunner.query(`DROP TYPE "public"."trends_phase_enum"`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "phase" text NOT NULL DEFAULT 'emerging'`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "source"`);
        await queryRunner.query(`CREATE TYPE "public"."trends_source_enum" AS ENUM('instagram', 'tiktok', 'x', 'pinterest', 'other')`);
        await queryRunner.query(`ALTER TABLE "trends" ADD "source" "public"."trends_source_enum" NOT NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_d2ca4e689a49cafa0702b4ef91f"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_06e561922fa92be30f2d032a1e9" PRIMARY KEY ("trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "saves" ALTER COLUMN "trend_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_06e561922fa92be30f2d032a1e9"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_e8cf2737d1d478c7a7511e9c65c" PRIMARY KEY ("user_id", "trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "FK_dbbc0f92c226a7590f0e468aff8" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "FK_7b8bc823fd09b6b5751919d4a60" FOREIGN KEY ("user_id") REFERENCES "user_profile"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clickouts" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clickouts" ADD CONSTRAINT "FK_21d5402615f2a6ec059af906b02" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "PK_74d230453e3a051cfef34e8fe77"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "PK_3661d9991554a583d54a7e4eb39" PRIMARY KEY ("trend_id", "id")`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "FK_d2b512a8b0994f668cef59f135a" FOREIGN KEY ("trend_id") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "content_type"`);
        await queryRunner.query(`ALTER TABLE "trends" DROP COLUMN "phase_updated_at"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "commerce_metadata"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "affiliate_network"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "merchant_name"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "is_authentic"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "is_sponsored"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "creator_id"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "saves" DROP CONSTRAINT "PK_e8cf2737d1d478c7a7511e9c65c"`);
        await queryRunner.query(`ALTER TABLE "saves" ADD CONSTRAINT "PK_b0ac3df08c51a42216cab1bf03a" PRIMARY KEY ("user_id", "trend_id")`);
        await queryRunner.query(`ALTER TABLE "saves" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "converted_at"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "converted"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "ip_hash"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "session_id"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "creator_id"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "source_type"`);
        await queryRunner.query(`DROP TYPE "public"."clickouts_source_type_enum"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "campaign_id"`);
        await queryRunner.query(`ALTER TABLE "clickouts" DROP COLUMN "trend_id"`);
        await queryRunner.query(`COMMENT ON COLUMN "sponsored_content"."placement_slot_weight" IS 'Weight for paid placement logic, NOT organic ranking'`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "placement_slot_weight"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "placement_bid"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "brand_id"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP CONSTRAINT "PK_3661d9991554a583d54a7e4eb39"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "PK_d2b512a8b0994f668cef59f135a" PRIMARY KEY ("trend_id")`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_profile" ADD "badges" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "user_profile" ADD "level" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "priority_score" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "bid_amount" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "advertiser_id" uuid`);
        await queryRunner.query(`DROP TABLE "creator_analytics"`);
        await queryRunner.query(`DROP TABLE "discount_codes"`);
        await queryRunner.query(`DROP TABLE "early_discovery_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."early_discovery_rewards_reward_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."early_discovery_rewards_phase_at_discovery_enum"`);
        await queryRunner.query(`DROP TABLE "score_events"`);
        await queryRunner.query(`DROP TYPE "public"."score_events_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."score_events_reason_enum"`);
        await queryRunner.query(`DROP TABLE "user_badges"`);
        await queryRunner.query(`DROP TYPE "public"."user_badges_badge_type_enum"`);
        await queryRunner.query(`DROP TABLE "trend_signals"`);
        await queryRunner.query(`DROP TYPE "public"."trend_signals_signal_type_enum"`);
        await queryRunner.query(`DROP TABLE "trend_phase_history"`);
        await queryRunner.query(`DROP TYPE "public"."trend_phase_history_new_phase_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trend_phase_history_old_phase_enum"`);
        await queryRunner.query(`DROP TABLE "interactions"`);
        await queryRunner.query(`DROP TABLE "creator_campaigns"`);
        await queryRunner.query(`DROP TYPE "public"."creator_campaigns_status_enum"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "creator_profiles"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD CONSTRAINT "FK_8e105b187066e0e5ad2be737a03" FOREIGN KEY ("advertiser_id") REFERENCES "user_profile"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
